### ISSUE TITLE
Integration into vrtk?

### ISSUE THREAD

**Issue by thestonefox** [SixWays/UnityVrTunnelling#3]
Hey,

We have this outstanding issue on vrtk

https://github.com/thestonefox/VRTK/issues/222

And this repo is usually the thing people turn to for vr tunnelling.

Is it something that can be brought into VRTK? or would it be better if we just made sure both were compatible and had this repo as the suggested way of doing tunnelling?

**Comment by SixWays** [comment]
Hey, in general I think it's worth keeping separate as one won't always want both in one project and this is definitely intended to be super-lightweight! That said, the license is MIT so of course you're more than welcome to roll it into VRTK if desired.

**Comment by thestonefox** [comment]
Awesome, thanks for letting us roll it in. I'll definitely splatter credit to this repo all over it :)

it's a really elegant solution!

**Comment by SixWays** [comment]
No worries, and cheers :)
