### ISSUE TITLE
Alternative background during tunneling

### ISSUE THREAD

**Issue by provencher** [SixWays/UnityVrTunnelling#4]
It would be interesting to have the possibility of rendering a fixed-head-tracking-consistent world, ideally with a grid, to further stabilize the player.

This effect is present in GoogleEarthVR, and Talos Principle VR

It is also discussed here
EMERGING STATIC IN THE PERIPHERY
https://developer.oculus.com/blog/research-into-comfortable-locomotion/

**Comment by thestonefox** [comment]
Just did this in VRTK. I'll raise a pull request tomorrow (maybe!) porting these features back into this repository if you want :)

example: https://twitter.com/The_StoneFox/status/928930264792883200

**Comment by thestonefox** [comment]
I have a branch on my fork of this repo that is supposed to add the cage background

https://github.com/thestonefox/UnityVrTunnelling/tree/feat/cage-skybox

It's not working at the moment (it's pretty much the same logic as in the VRTK version).

I'll try look more next week if I can, or if someone can take the concept and make it work then even better!

**Comment by SixWays** [comment]
Implemented!
