### ISSUE TITLE
When Iris converges to a small dot it separates into two dots

### ISSUE THREAD

**Issue by thestonefox** [SixWays/UnityVrTunnelling#5]
The iris is currently applied to each camera so when the iris converges down very small the iris is clearly visible in both lenses.

(Note, we've fixed this in the VRTK version, i'll raise a separate pull request bringing the fix back into this repo!)

**Comment by SixWays** [comment]
Do you mean as opposed to drawing one iris over the entire screen buffer? If so, in earlier versions that's how it worked but I found it to be weird...

**Comment by SixWays** [comment]
Fixed!
